import java.util.Scanner;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import net.glxn.qrgen.core.image.ImageType;
import net.glxn.qrgen.javase.QRCode;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;

import static java.lang.String.format;

import java.io.*;
import java.io.IOException;
import java.util.Hashtable;

import com.google.zxing.WriterException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Muhammad Saad
 */
public class Create_QR extends javax.swing.JFrame {

    /**
     * Creates new form Create_QR
     */
    public Create_QR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        C = new javax.swing.JTabbedPane();
        WIFI = new javax.swing.JPanel();
        WIFIButton = new javax.swing.JButton();
        SSID = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        Caption = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        URL = new javax.swing.JPanel();
        Image1 = new javax.swing.JLabel();
        URLTextBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        URLButton = new javax.swing.JButton();
        Caption1 = new javax.swing.JLabel();
        Text = new javax.swing.JPanel();
        Image2 = new javax.swing.JLabel();
        TextTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextButton = new javax.swing.JButton();
        Caption2 = new javax.swing.JLabel();
        ContactInformation = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Caption3 = new javax.swing.JLabel();
        ContactNameTextBox = new javax.swing.JTextField();
        ContactButton = new javax.swing.JButton();
        Image3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        ContactCompanyTextBox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ContactTitleTextBox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ContactPhoneTextBox = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ContactEmailTextBox = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ContactAddressTextBox = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ContactWebsiteTextBox = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ContactMemoTextBox = new javax.swing.JTextArea();
        Email = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Caption4 = new javax.swing.JLabel();
        EmailTextBox = new javax.swing.JTextField();
        EmailButton = new javax.swing.JButton();
        Image4 = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Caption5 = new javax.swing.JLabel();
        PhoneTextBox = new javax.swing.JTextField();
        PhoneButton = new javax.swing.JButton();
        Image5 = new javax.swing.JLabel();
        SMS = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Caption6 = new javax.swing.JLabel();
        SMSPhoneTextBox = new javax.swing.JTextField();
        SMSButton = new javax.swing.JButton();
        Image6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SMSTextTextBox = new javax.swing.JTextArea();
        Geo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Caption7 = new javax.swing.JLabel();
        LatitudeTextBox = new javax.swing.JTextField();
        GeoButton = new javax.swing.JButton();
        Image7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        LongitudeTextBox = new javax.swing.JTextField();
        CalendarEvent = new javax.swing.JPanel();
        EventButton = new javax.swing.JButton();
        Caption8 = new javax.swing.JLabel();
        Image8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        EventTitleTextBox = new javax.swing.JTextField();
        EventStartDateTextBox = new javax.swing.JTextField();
        EventStartTimeTextBox = new javax.swing.JTextField();
        EventEndDateTextBox = new javax.swing.JTextField();
        EventEndTimeTextBox = new javax.swing.JTextField();
        EventLocationTextBox = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        EventDescriptionTextBox = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QR Code Genreator");
        setResizable(false);

        WIFIButton.setText("Generate");
        WIFIButton.setBorder(null);
        WIFIButton.setPreferredSize(new java.awt.Dimension(80, 25));
        WIFIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WIFIButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("True");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("False");

        jLabel1.setText("Network SSID");

        jLabel2.setText("Password");

        jLabel3.setText("Hidden SSID");

        jLabel4.setText("Security");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("WEP");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("WPA");

        Caption.setText("To Be Created here");

        Image.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout WIFILayout = new javax.swing.GroupLayout(WIFI);
        WIFI.setLayout(WIFILayout);
        WIFILayout.setHorizontalGroup(
            WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WIFILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Password)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(SSID, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WIFIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(WIFILayout.createSequentialGroup()
                            .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jRadioButton4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton3))
                        .addGroup(WIFILayout.createSequentialGroup()
                            .addComponent(jRadioButton2)
                            .addGap(40, 40, 40)
                            .addComponent(jRadioButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WIFILayout.createSequentialGroup()
                        .addComponent(Caption)
                        .addGap(102, 102, 102)))
                .addContainerGap())
        );
        WIFILayout.setVerticalGroup(
            WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WIFILayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WIFILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addComponent(WIFIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(WIFILayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(Caption, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        C.addTab("WI-FI", WIFI);

        Image1.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Your URL");

        URLButton.setText("Generate");
        URLButton.setPreferredSize(new java.awt.Dimension(80, 25));
        URLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLButtonActionPerformed(evt);
            }
        });

        Caption1.setText("To Be Created here");

        javax.swing.GroupLayout URLLayout = new javax.swing.GroupLayout(URL);
        URL.setLayout(URLLayout);
        URLLayout.setHorizontalGroup(
            URLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(URLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(URLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(URLLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caption1)
                        .addGap(119, 119, 119))
                    .addGroup(URLLayout.createSequentialGroup()
                        .addGroup(URLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(URLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URLTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        URLLayout.setVerticalGroup(
            URLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(URLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(URLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caption1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(URLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(URLLayout.createSequentialGroup()
                        .addComponent(URLTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(URLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Image1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        C.addTab("URL", URL);

        Image2.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Text");
        jLabel8.setToolTipText("");

        TextButton.setText("Generate");
        TextButton.setPreferredSize(new java.awt.Dimension(80, 25));
        TextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextButtonActionPerformed(evt);
            }
        });

        Caption2.setText("To Be Created here");

        javax.swing.GroupLayout TextLayout = new javax.swing.GroupLayout(Text);
        Text.setLayout(TextLayout);
        TextLayout.setHorizontalGroup(
            TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextLayout.createSequentialGroup()
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextLayout.createSequentialGroup()
                        .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TextLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(TextLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Caption2)
                    .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
        );
        TextLayout.setVerticalGroup(
            TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextLayout.createSequentialGroup()
                .addGroup(TextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TextLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Caption2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Image2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TextLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.getAccessibleContext().setAccessibleName("Your Text");

        C.addTab("Text", Text);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Name");

        Caption3.setText("To Be Created here");

        ContactButton.setText("Generate");
        ContactButton.setPreferredSize(new java.awt.Dimension(80, 25));
        ContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactButtonActionPerformed(evt);
            }
        });

        Image3.setPreferredSize(new java.awt.Dimension(300, 300));

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("vCard");

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("MECARD");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Company");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Title");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Phone Number\t");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Email");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Address");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Website");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Memo");

        ContactMemoTextBox.setColumns(20);
        ContactMemoTextBox.setRows(5);
        jScrollPane2.setViewportView(ContactMemoTextBox);

        javax.swing.GroupLayout ContactInformationLayout = new javax.swing.GroupLayout(ContactInformation);
        ContactInformation.setLayout(ContactInformationLayout);
        ContactInformationLayout.setHorizontalGroup(
            ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContactNameTextBox)
                            .addComponent(ContactCompanyTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactTitleTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(ContactAddressTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(ContactWebsiteTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContactPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addGroup(ContactInformationLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(ContactEmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Caption3))
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Image3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(228, 228, 228))
        );
        ContactInformationLayout.setVerticalGroup(
            ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactInformationLayout.createSequentialGroup()
                .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(ContactNameTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ContactCompanyTextBox)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ContactTitleTextBox)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ContactPhoneTextBox)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ContactEmailTextBox)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ContactAddressTextBox)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(ContactWebsiteTextBox)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContactInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContactInformationLayout.createSequentialGroup()
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton6))
                            .addGroup(ContactInformationLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(ContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(ContactInformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Caption3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Image3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        C.addTab("Contact Information", ContactInformation);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Email");

        Caption4.setText("To Be Created here");

        EmailButton.setText("Generate");
        EmailButton.setPreferredSize(new java.awt.Dimension(80, 25));
        EmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailButtonActionPerformed(evt);
            }
        });

        Image4.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout EmailLayout = new javax.swing.GroupLayout(Email);
        Email.setLayout(EmailLayout);
        EmailLayout.setHorizontalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caption4)
                        .addGap(119, 119, 119))
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Image4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        EmailLayout.setVerticalGroup(
            EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caption4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmailLayout.createSequentialGroup()
                        .addComponent(EmailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Image4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        C.addTab("Email", Email);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Phone Number");

        Caption5.setText("To Be Created here");

        PhoneButton.setText("Generate");
        PhoneButton.setPreferredSize(new java.awt.Dimension(80, 25));
        PhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneButtonActionPerformed(evt);
            }
        });

        Image5.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout PhoneNumberLayout = new javax.swing.GroupLayout(PhoneNumber);
        PhoneNumber.setLayout(PhoneNumberLayout);
        PhoneNumberLayout.setHorizontalGroup(
            PhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneNumberLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhoneNumberLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caption5)
                        .addGap(119, 119, 119))
                    .addGroup(PhoneNumberLayout.createSequentialGroup()
                        .addGroup(PhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Image5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PhoneNumberLayout.setVerticalGroup(
            PhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhoneNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caption5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PhoneNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhoneNumberLayout.createSequentialGroup()
                        .addComponent(PhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Image5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        C.addTab("Phone Number", PhoneNumber);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Phone Number");

        Caption6.setText("To Be Created here");

        SMSButton.setText("Generate");
        SMSButton.setPreferredSize(new java.awt.Dimension(80, 25));
        SMSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMSButtonActionPerformed(evt);
            }
        });

        Image6.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Text");

        SMSTextTextBox.setColumns(20);
        SMSTextTextBox.setRows(5);
        jScrollPane1.setViewportView(SMSTextTextBox);

        javax.swing.GroupLayout SMSLayout = new javax.swing.GroupLayout(SMS);
        SMS.setLayout(SMSLayout);
        SMSLayout.setHorizontalGroup(
            SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SMSLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SMSLayout.createSequentialGroup()
                        .addGroup(SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(SMSPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(SMSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SMSLayout.createSequentialGroup()
                        .addComponent(Caption6)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SMSLayout.createSequentialGroup()
                        .addComponent(Image6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        SMSLayout.setVerticalGroup(
            SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SMSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caption6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SMSLayout.createSequentialGroup()
                        .addComponent(Image6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SMSLayout.createSequentialGroup()
                        .addComponent(SMSPhoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(SMSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );

        C.addTab("SMS", SMS);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("latitude");

        Caption7.setText("To Be Created here");

        GeoButton.setText("Generate");
        GeoButton.setPreferredSize(new java.awt.Dimension(80, 25));
        GeoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeoButtonActionPerformed(evt);
            }
        });

        Image7.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("longitude");

        javax.swing.GroupLayout GeoLayout = new javax.swing.GroupLayout(Geo);
        Geo.setLayout(GeoLayout);
        GeoLayout.setHorizontalGroup(
            GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caption7)
                        .addGap(119, 119, 119))
                    .addGroup(GeoLayout.createSequentialGroup()
                        .addGroup(GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LatitudeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GeoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(LongitudeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(Image7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        GeoLayout.setVerticalGroup(
            GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caption7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeoLayout.createSequentialGroup()
                        .addComponent(LatitudeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LongitudeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(GeoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Image7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        C.addTab("Geo Location", Geo);

        EventButton.setText("Generate");
        EventButton.setPreferredSize(new java.awt.Dimension(80, 25));
        EventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventButtonActionPerformed(evt);
            }
        });

        Caption8.setText("To Be Created here");

        Image8.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Event Title");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Start Date");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Start Time");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("End Date ");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("End Time");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Location");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Description");

        EventDescriptionTextBox.setColumns(20);
        EventDescriptionTextBox.setRows(5);
        jScrollPane3.setViewportView(EventDescriptionTextBox);

        javax.swing.GroupLayout CalendarEventLayout = new javax.swing.GroupLayout(CalendarEvent);
        CalendarEvent.setLayout(CalendarEventLayout);
        CalendarEventLayout.setHorizontalGroup(
            CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalendarEventLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalendarEventLayout.createSequentialGroup()
                        .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EventTitleTextBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EventStartTimeTextBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EventEndDateTextBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EventStartDateTextBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EventEndTimeTextBox, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(CalendarEventLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(32, 32, 32)
                        .addComponent(EventLocationTextBox))
                    .addGroup(CalendarEventLayout.createSequentialGroup()
                        .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CalendarEventLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CalendarEventLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(EventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Image8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caption8))
                .addGap(59, 59, 59))
        );
        CalendarEventLayout.setVerticalGroup(
            CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalendarEventLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel23)
                    .addComponent(EventTitleTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EventStartDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(EventStartTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EventEndDateTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(EventEndTimeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(EventLocationTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalendarEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CalendarEventLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel30)))
                .addGap(18, 18, 18)
                .addComponent(EventButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalendarEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Caption8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Image8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        C.addTab("Calender Event", CalendarEvent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WIFIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WIFIButtonActionPerformed
        try {
            
            // getting input From User throug some TextFields and Radio buttons
            String ssid = SSID.getText();
            String password = Password.getText();
            String isHidden = getSelectedButtonText(buttonGroup1);
            String security = getSelectedButtonText(buttonGroup2);
            
            // Encoding String is the string will be converted to QR Code
            // the part WIFI: is the way to make Scanned QR Code connecting Automatically in your Wifi Preferences
            String EncodingString = "WIFI:S:%s;T:%s;P:%s;H:%s;";
            EncodingString = format(EncodingString, ssid, security, password, isHidden);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);

            String ImgName = ssid + ".png";
            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            
            
            ImageIcon img = new ImageIcon(ImgName);
            Caption.setText("Your QR Code :)");
            Image.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_WIFIButtonActionPerformed

    private void URLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLButtonActionPerformed
        //URL 

        try {

            String URL = URLTextBox.getText();
            String[] A = URL.split("\\/");

            String EncodingString = URL;
            //  EncodingString = format(EncodingString, URL);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);
            // JOptionPane.showMessageDialog(new JFrame(), URL, A[2], JOptionPane.INFORMATION_MESSAGE);
            String ImgName = A[2] + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption.setText("Your QR Code :)");
            Image1.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_URLButtonActionPerformed

    private void TextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextButtonActionPerformed
        // TODO add your handling code here:
        try {

            String Text = TextTextBox.getText();

            String EncodingString = Text;

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);
            JOptionPane.showMessageDialog(new JFrame(), EncodingString, Text, JOptionPane.INFORMATION_MESSAGE);
            String ImgName = Text.trim() + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption2.setText("Your QR Code :)");
            Image2.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_TextButtonActionPerformed

    private void EmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailButtonActionPerformed
        // TODO add your handling code here:

        try {

            String Email = EmailTextBox.getText();
            String[] A = Email.split("@");

            String EncodingString = "mailto:%s";
            EncodingString = format(EncodingString, Email);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);
            JOptionPane.showMessageDialog(new JFrame(), EncodingString, A[0], JOptionPane.INFORMATION_MESSAGE);
            String ImgName = A[0] + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption4.setText("Your QR Code :)");
            Image4.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_EmailButtonActionPerformed

    private void PhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneButtonActionPerformed
        // TODO add your handling code here:

        try {

            String PhoneNumber = PhoneTextBox.getText();

            String EncodingString = "tel:%s";
            EncodingString = format(EncodingString, PhoneNumber);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);
            JOptionPane.showMessageDialog(new JFrame(), EncodingString, PhoneNumber, JOptionPane.INFORMATION_MESSAGE);
            String ImgName = PhoneNumber + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption5.setText("Your QR Code :)");
            Image5.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_PhoneButtonActionPerformed

    private void SMSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMSButtonActionPerformed
        // TODO add your handling code here:
        try {

            String PhoneNumber = SMSPhoneTextBox.getText();
            String Text = SMSTextTextBox.getText();

            String EncodingString = "smsto:%s:%s";
            EncodingString = format(EncodingString, PhoneNumber, Text);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);
            JOptionPane.showMessageDialog(new JFrame(), EncodingString, PhoneNumber, JOptionPane.INFORMATION_MESSAGE);
            String ImgName = "SMS to " + PhoneNumber + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption6.setText("Your QR Code :)");
            Image6.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_SMSButtonActionPerformed

    private void GeoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeoButtonActionPerformed
        // TODO add your handling code here:"geo:40.71872,-73.98905,100"

        try {

            String Latitude = LatitudeTextBox.getText();
            String Longitude = LongitudeTextBox.getText();

            String EncodingString = "geo:%s,%s,100";
            EncodingString = format(EncodingString, Latitude, Longitude);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);
            JOptionPane.showMessageDialog(new JFrame(), EncodingString, EncodingString, JOptionPane.INFORMATION_MESSAGE);
            String ImgName = EncodingString + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption7.setText("Your QR Code :)");
            Image7.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                    "QR Code image created successfully!", "Done",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GeoButtonActionPerformed

    private void ContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactButtonActionPerformed
        // TODO add your handling code here:

        try {

            String Name = ContactNameTextBox.getText();
            String Company = ContactCompanyTextBox.getText();
            String Title = ContactTitleTextBox.getText();
            String PhoneNumber = ContactPhoneTextBox.getText();
            String Email = ContactEmailTextBox.getText();
            String Address = ContactAddressTextBox.getText();
            String Website = ContactWebsiteTextBox.getText();
            String Memo = ContactMemoTextBox.getText();
            String EncodingOption = getSelectedButtonText(buttonGroup3);

            if (EncodingOption == "vCard") {
                //JOptionPane.showMessageDialog(new JFrame(), isHidden, security, JOptionPane.INFORMATION_MESSAGE);
                String EncodingString = "BEGIN:VCARD\n"
                        + "VERSION:3.0\n"
                        + "N:%s\n"
                        + "ORG:%s\n"
                        + "TITLE:%s\n"
                        + "TEL:%s\n"
                        + "URL:%s\n"
                        + "EMAIL:%s\n"
                        + "ADR:%s\n"
                        + "NOTE:%s\n"
                        + "END:VCARD\n";
                EncodingString = format(EncodingString, Name, Company, Title, PhoneNumber, Website, Email, Address, Memo);

                MultiFormatWriter writer = new MultiFormatWriter();
                Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                        = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

                hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

                BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);

                String ImgName = Name + "_vCard" + ".png";

                MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
                ImageIcon img = new ImageIcon(ImgName);
                Caption3.setText("Your QR Code :)");
                Image3.setIcon(img);
                JOptionPane.showMessageDialog(new JFrame(),
                        "QR Code image created successfully!", "Done",
                        JOptionPane.INFORMATION_MESSAGE);

            } else {
                //JOptionPane.showMessageDialog(new JFrame(), isHidden, security, JOptionPane.INFORMATION_MESSAGE);
                String EncodingString = "MECARD:N:%s;ORG:%s;TEL:%s;URL:%s;EMAIL:%s;ADR:%s;NOTE:%s;;";
                EncodingString = format(EncodingString, Name, Company, PhoneNumber, Website, Email, Address, Memo, Title);

                MultiFormatWriter writer = new MultiFormatWriter();
                Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                        = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

                hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

                BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);

                String ImgName = Name + "_MECard" + ".png";

                MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
                ImageIcon img = new ImageIcon(ImgName);
                Caption3.setText("Your QR Code :)");
                Image3.setIcon(img);
                JOptionPane.showMessageDialog(new JFrame(),
                        "QR Code image created successfully!", "Done",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_ContactButtonActionPerformed

    private void EventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventButtonActionPerformed
        // TODO add your handling code here:
        try {
            String Title = EventTitleTextBox.getText();
            String StartDate = EventStartDateTextBox.getText();
            String StartTime = EventStartTimeTextBox.getText();
            String EndDate = EventEndDateTextBox.getText();
            String EndTime = EventEndDateTextBox.getText();
            String Location = EventLocationTextBox.getText();
            String Description = EventDescriptionTextBox.getText();

            // to be done -->DTSTART:20181127T222000Z
            String DTSTART = StartDate + StartTime;
            String DTEND = EndDate + EndTime;

            //JOptionPane.showMessageDialog(new JFrame(), isHidden, security, JOptionPane.INFORMATION_MESSAGE);
            String EncodingString = "BEGIN:VEVENT\n"
                    + "SUMMARY:%s\n"
                    + "DTSTART:%s\n"
                    + "DTEND:%s\n"
                    + "LOCATION:%s\n"
                    + "DESCRIPTION:%s\n"
                    + "END:VEVENT";

            EncodingString = format(EncodingString, Title, DTSTART, DTEND, Location, Description);

            MultiFormatWriter writer = new MultiFormatWriter();
            Hashtable<EncodeHintType, ErrorCorrectionLevel> hints
                    = new Hashtable<EncodeHintType, ErrorCorrectionLevel>();

            hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);

            BitMatrix bitMatrix = writer.encode(EncodingString, BarcodeFormat.QR_CODE, 300, 300, hints);

            String ImgName = Title + ".png";

            MatrixToImageWriter.writeToFile(bitMatrix, "png", new File(ImgName));
            ImageIcon img = new ImageIcon(ImgName);
            Caption3.setText("Your QR Code :)");
            Image3.setIcon(img);
            JOptionPane.showMessageDialog(new JFrame(),
                        "QR Code image created successfully!", "Done",
                        JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_EventButtonActionPerformed
    //<editor-fold defaultstate="collapsed" desc=" MyMethods   ">
    public String getTime(String date,String Time) {
        String res="";
        
        return res;
    }

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc=" Genreated And Main   ">

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //Caption.setText("");
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_QR().setVisible(true);
            }
        });
    }

    //<editor-fold defaultstate="collapsed" desc=" Variables declaration  (optional) ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane C;
    private javax.swing.JPanel CalendarEvent;
    private javax.swing.JLabel Caption;
    private javax.swing.JLabel Caption1;
    private javax.swing.JLabel Caption2;
    private javax.swing.JLabel Caption3;
    private javax.swing.JLabel Caption4;
    private javax.swing.JLabel Caption5;
    private javax.swing.JLabel Caption6;
    private javax.swing.JLabel Caption7;
    private javax.swing.JLabel Caption8;
    private javax.swing.JTextField ContactAddressTextBox;
    private javax.swing.JButton ContactButton;
    private javax.swing.JTextField ContactCompanyTextBox;
    private javax.swing.JTextField ContactEmailTextBox;
    private javax.swing.JPanel ContactInformation;
    private javax.swing.JTextArea ContactMemoTextBox;
    private javax.swing.JTextField ContactNameTextBox;
    private javax.swing.JTextField ContactPhoneTextBox;
    private javax.swing.JTextField ContactTitleTextBox;
    private javax.swing.JTextField ContactWebsiteTextBox;
    private javax.swing.JPanel Email;
    private javax.swing.JButton EmailButton;
    private javax.swing.JTextField EmailTextBox;
    private javax.swing.JButton EventButton;
    private javax.swing.JTextArea EventDescriptionTextBox;
    private javax.swing.JTextField EventEndDateTextBox;
    private javax.swing.JTextField EventEndTimeTextBox;
    private javax.swing.JTextField EventLocationTextBox;
    private javax.swing.JTextField EventStartDateTextBox;
    private javax.swing.JTextField EventStartTimeTextBox;
    private javax.swing.JTextField EventTitleTextBox;
    private javax.swing.JPanel Geo;
    private javax.swing.JButton GeoButton;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Image3;
    private javax.swing.JLabel Image4;
    private javax.swing.JLabel Image5;
    private javax.swing.JLabel Image6;
    private javax.swing.JLabel Image7;
    private javax.swing.JLabel Image8;
    private javax.swing.JTextField LatitudeTextBox;
    private javax.swing.JTextField LongitudeTextBox;
    private javax.swing.JTextField Password;
    private javax.swing.JButton PhoneButton;
    private javax.swing.JPanel PhoneNumber;
    private javax.swing.JTextField PhoneTextBox;
    private javax.swing.JPanel SMS;
    private javax.swing.JButton SMSButton;
    private javax.swing.JTextField SMSPhoneTextBox;
    private javax.swing.JTextArea SMSTextTextBox;
    private javax.swing.JTextField SSID;
    private javax.swing.JPanel Text;
    private javax.swing.JButton TextButton;
    private javax.swing.JTextField TextTextBox;
    private javax.swing.JPanel URL;
    private javax.swing.JButton URLButton;
    private javax.swing.JTextField URLTextBox;
    private javax.swing.JPanel WIFI;
    private javax.swing.JButton WIFIButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
    //</editor-fold>
}
